title: My projects
author: Victor Rabinovich
email: vityarabinovich@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is a website of the different projects and ideas of Victor Rabinovich aka Rabinvic.
  Here you will find projects I have completed as well as possibly any ideas or projects that
  I'm currently working on.

# social links
twitter_username: Rabinvic # DO NOT include the @ character, or else the build will fail!
github_username:  Rabinvic # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
